### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined for `no-debug`

### ISSUE THREAD

**Issue by tdeekens** [testing-library/eslint-plugin-testing-library#101]
We adopted the react preset recently and are seeing failing builds on CI with the error `TypeError: Cannot read property 'name' of undefined`. Which seems to originate from this code:

```js
ImportDeclaration(node) {
    const screenModuleName = LIBRARY_MODULES_WITH_SCREEN.find(
      module => module === node.source.value
    );

    if (
      screenModuleName &&
      node.specifiers.some(
        specifier => specifier.imported.name === 'screen'
      )
    ) {
      hasImportedScreen = true;
    }
},
```

in no-debug.js on line 95.

<img width="1226" alt="CleanShot 2020-03-30 at 10 29 58@2x" src="https://user-images.githubusercontent.com/1877073/77891713-ab5b9c00-7271-11ea-8a98-9f60e08ac7fb.png">

We are also seeing the error on a GitHub Action build to inspect for you.

https://github.com/commercetools/merchant-center-application-kit/pull/1419/checks?check_run_id=544774992

**Comment by Belco90** [comment]
Hey Tobias, thanks for reporting the error. Sorry about this, I'll take a look a it this morning, should be easy to fix. Pretty awesome how much info you added to the issue :)

**Comment by tdeekens** [comment]
You're welcome. I do some Open Source myself so I know how hard (also emotionally) it can be to get an issue with little to no context 😄. Thanks for the quick response.

**Comment by Belco90** [comment]
I found the issue: wildcard imports like `import * as rtl from '@testing-library/react';` are not taken into account properly. Checking how to fix it properly.

**Comment by Belco90** [comment]
@tdeekens fixed btw, just waiting for the PR to be approved. I'm checking meanwhile another rule that could be affected by the same issue!

**Comment by tdeekens** [comment]
Wow, super fast. Thanks!

**Comment by tdeekens** [comment]
Thanks bot. Thanks human :)

**Comment by Belco90** [comment]
@all-contributors please add @tdeekens for bug
