### ISSUE TITLE
Restrict using `cy.query*`

### ISSUE THREAD

**Issue by doniyor2109** [testing-library/eslint-plugin-testing-library#109]
Recently `cypress-testing-library` depracated `query*` methods. https://github.com/testing-library/cypress-testing-library/pull/130

It would be great to warn this behavior also.

**Comment by Belco90** [comment]
Thanks. We have [this issue](#80) for adding more shareable configs to the plugin. You can see there there was some discussion around cypress, so I'll close this ticket in favor of keep the discussion there until we can add those new configs.
