### ISSUE TITLE
Using query* variants for anything except checking for non-existance

### ISSUE THREAD

**Issue by tvthatsme** [testing-library/eslint-plugin-testing-library#126]
I found this project from @kentcdodds blog post [Common mistakes with React Testing Library](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library?ck_subscriber_id=363853600). Wish I had known about it earlier!

One of the mistakes that stood out to me was "**using query* variants for anything except checking for non-existance**".

```
// ❌
expect(screen.queryByRole('alert')).toBeInTheDocument()
// ✅
expect(screen.getByRole('alert')).toBeInTheDocument()
expect(screen.queryByRole('alert')).not.toBeInTheDocument()
```

After installing this plugin, it seems like there is no rule "no-query-except-for-existance-assertion" or something along those lines. Did I miss something? If not, I'd like to contribute that!

**Comment by Belco90** [comment]
Hello Timothy! I’m glad you hace discovered the plugin and find it useful :)

There is no rule so picky as what’s mentioned in that common mistakes post, but there is a rule that will make sure you use proper query when asserting presence of an element: [prefer-presence-queries](https://github.com/testing-library/eslint-plugin-testing-library/blob/master/docs/rules/prefer-presence-queries.md)

I think this one should cover the main use cases around it. Let me know what you think!

**Comment by tvthatsme** [comment]
Hey Mario, thanks for the answer. I guess that's what I was looking for :) Probably better to keep it a little less picky anyways.
