### ISSUE TITLE
No Recommended Rule Column

### ISSUE THREAD

**Issue by HaveSpacesuit** [testing-library/eslint-plugin-testing-library#135]
The readme says "you can find more info about enabled rules in Supported Rules section within Recommended column", but there is no recommended column in the rule list.

![image](https://user-images.githubusercontent.com/15036346/82077906-d37a4f80-96a5-11ea-9574-43db1628bd5a.png)

**Comment by Belco90** [comment]
Hi Eric! Sorry, this is a mistake in the README. It should say:

> you can find more info about enabled rules in Supported Rules section within **Configurations** column
