### ISSUE TITLE
Support ESLint 7.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [testing-library/eslint-plugin-testing-library#138]
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

It would be awesome to have official ESLint 7 support. 👊
I'm happy to help where I can of course 🙂

**Comment by Belco90** [comment]
Hey Michael! Thanks for your suggestion and help. Indeed, it would be nice to update the plugin to get compatibility with ESLint v7. I was thinking about adding an ESLint matrix to CI in a similar way as [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react/blob/master/.travis.yml) address it. I don't know if there is a better approach for that.

Anyway, I don't expect to cover so many node and ESLint versions as that plugin. I think just with node 10.12, 12 and 14 (we already have this) and ESLint v5, v6 and v7 (this is missing at the moment) would be enough.

Thoughts?

**Comment by MichaelDeBoey** [comment]
@Belco90 I've opened #139 to support ESLint 7.x

**Comment by Belco90** [comment]
Oh wow, amazing job with that one and all related PRs mate 🎉

**Comment by Belco90** [comment]
I still think we should merge this one. All the tests are passing for ESLint 5, 6 and 7. We are not affected by breaking changes from v7. It doesn't seem the dependencies not upgraded to v7 yet are breaking anything in our side.

**Comment by nickmccurdy** [comment]
Can they be installed with yarn though? If I remember correctly, yarn errors on peer dependency warnings by default. Even if a dependency of this package works, if it doesn't say it works with ESLint 7 and that's the only pinned version, the entire installation would fail.

**Comment by Belco90** [comment]
First notice I have about it. I need to check that behavior when installing with yarn.

**Comment by BridgeAR** [comment]
Installing with yarn works properly as well.
