### ISSUE TITLE
[Technical] Add baseUrl in tsconfig.json in order to avoid relative paths

### ISSUE THREAD

**Issue by gndelia** [testing-library/eslint-plugin-testing-library#140]
Now that the library has been migrated to typescript 🎉  I think we could use the [baseUrl option](https://www.typescriptlang.org/tsconfig#baseUrl)

```json
"baseUrl": "./
```

By doing so, we could set all the imports as absolute from that URL. So, for example, [this import](https://github.com/testing-library/eslint-plugin-testing-library/blob/master/tests/lib/rules/no-debug.test.ts#L2)

```ts
import rule, { RULE_NAME } from '../../../lib/rules/no-debug';
```

can be now converted to 
```ts
import rule, { RULE_NAME } from 'lib/rules/no-debug';
```

and the same applies to all import. I usually find this more readable 

In addition to that, when moving files, they get updated automatically 😄

**Comment by Belco90** [comment]
Of course! We didn't realize about this when moving to TS. I'll try to sort this soon. Thanks!

**Comment by Belco90** [comment]
Mmm ok, I think we didn't do anything related to that because we are only including `/lib` in ts-config (to avoid including them in final bundle), so we can't use absolute imports somewhere else like tests.

I don't know if we should update only those imports under lib folder then or use a different approach.

**Comment by gndelia** [comment]
I think baseUrl only affects module resolution, those files that are excluded from under `lib` perhaps will be ignored. That's not an issue, as you import from lib, but you're not importing something else (as the implementation does not import the tests)

I'd give it a try to see if affects the final bundle. In addition to that, perhaps we could use `"baseUrl": "./lib"` if all absolute imports are `lib` related

**Comment by timdeschryver** [comment]
I think a better option would be to use [path-mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) for this.

**Comment by gndelia** [comment]
I did a bit of work on this one. It compiles and the tests pass.

However, when I compared the `dist` before and after the changes, while the code is exactly the same, the path in `require` have changed (of course!) from relative paths to absolute ones. Not quite sure if that will work automatically. I will do further work, but this probably is a low priority 😅 

I think `npm link` should help me to use this version in a real project, just to verify it works

**Comment by Belco90** [comment]
I can publish a pre-release version if that's easier.

**Comment by gndelia** [comment]
After doing some testing, and finding some interesting notes like this https://github.com/microsoft/TypeScript/issues/16640 and this https://stackoverflow.com/questions/56949487/how-to-have-absolute-import-paths-in-a-library-project

there's no way to fully implement this without involving a post-build task or webpack to translate the absolute paths in compile/build time to relative paths that will run on runtime.

TS only uses those absolute paths for type-checking but does not perform any translation. That means we can use them under `tests` folder but we can't under `libs`, so probably it's not worth the effort.

Let me know your thoughts, but we should probably close this one.

**Comment by nickmccurdy** [comment]
I've maintained a library using custom paths, and it's not worth the effort. I spent way more time trying to fix tooling bugs than I saved by simplifying imports, and you can still simply relative imports by just moving files around.

**Comment by Belco90** [comment]
Ok so it seems we are introducing more problems than we solve. Should we close the issue then?

**Comment by gndelia** [comment]
yeah. Closing
