### ISSUE TITLE
prefer-wait-for rule autofix is modifying Cypress wait() functions

### ISSUE THREAD

**Issue by Miguelerja** [testing-library/eslint-plugin-testing-library#151]
Hello,

I have tried to add the rule 'prefer-wait-for' to my code but an unexpected interaction is provoked with my Cypress files. The autofix from the rule is also changing the calls to cy.Wait() for cy.WaitFor() in my Cypress test files

<img width="723" alt="Screenshot 2020-06-09 at 14 04 13" src="https://user-images.githubusercontent.com/42043025/84145627-85fdc200-aa5a-11ea-83f0-52b795da1ee3.png">

**Comment by Belco90** [comment]
Hi Miguel! Indeed this is a bug, the rule shouldn't apply to anything but testing library utils.

**Comment by timdeschryver** [comment]
Let me try to see if I can fix this, seems fair as I've introduced this bug 😅
