### ISSUE TITLE
new rule: no-container

### ISSUE THREAD

**Issue by nickmccurdy** [testing-library/eslint-plugin-testing-library#171]
__Inspiration:__ [Using container to query for elements](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-container-to-query-for-elements)

This would error on `container` methods like `querySelector` that are often used instead of get/query functions, as there might be other reasons why you'd need to access the container in a test (such as assertions). It would be nice to give suggestions of specific get/query functions as well, but I'm not sure how far we could get.

**Comment by thebinaryfelix** [comment]
Hi, everyone! I'd like to help implementing this rule, could I be assigned to it @nickmccurdy ?

**Comment by gndelia** [comment]
Sure, it's all yours 😄  You might want to review #165 as well because there were some mentions about this ticket.

**Comment by thebinaryfelix** [comment]
Thanks @gndelia !
