### ISSUE TITLE
New rule: no-rerender

### ISSUE THREAD

**Issue by gndelia** [testing-library/eslint-plugin-testing-library#178]
`render` method offers a method called [rerender](https://testing-library.com/docs/native-testing-library/api#rerender). This one allows forcing a rerender with new props, though it'd be ideal to cause those changes by interactions (for example using `userEvent`), instead of updating the props.

I was thinking of a rule that disables its usage could be useful. I am not sure if it should be recommended or not.

This method is not exported from `screen` - it's only available from `render` result.

Thoughts?

**Comment by nickmccurdy** [comment]
I do see some value in using this to integration/unit test reusable components that need to react to prop changes. However there is some inconsistency with how we plan on recommending `prefer-screen-queries` in [v4](https://github.com/testing-library/eslint-plugin-testing-library/milestone/2). Should we add this API to screen or allow it in `prefer-screen-queries`?

**Comment by gndelia** [comment]
>I do see some value in using this to integration/unit test reusable components that need to react to prop changes.

True, and that's probably the reason why this rule should not be `recommended` one. However, it might be useful as a rule per se. I don't think it should be a required rule for v4

> Should we add this API to screen or allow it in prefer-screen-queries?

Yeah, it should be probably an exception in `prefer-screen-queries`. Not sure if it currently is or not - we might want to add some test cases there.

**Comment by nickmccurdy** [comment]
@benmonro Thoughts?

**Comment by benmonro** [comment]
hmm, yeah i like the concept, not sure I'd be able to turn it on as an `error` but I could see it being useful as a `warn`

I agree w/ the sentiment that you should _try_ to use user interactions instead of rerender, but that can sometimes mean biting off a lot more than you can chew in a test, especially in big (poorly factored) redux applications.  

I do however think prefer-screen-queries should be separate from this one, since it's not actually a query.

**Comment by benmonro** [comment]
is it possible to recommend something as a warn?  I know we can do that in the recommended config...

**Comment by gndelia** [comment]
> I do however think prefer-screen-queries should be separate from this one, since it's not actually a query.

I agree. 

But I am not sure current implementation of that rule allows this, or if it throws an error when trying to use `rerender` as part of the destructuring.
 
I will check it later today, and if it works I will add some test cases and update the docs for that rule as a valid exception (as it's the only way to use it because it's not exported in `screen` object)

**Comment by Belco90** [comment]
I agree with @benmonro: separated rule, not enabled by default as error. We can enable it as warning, I think that could be a good reminder to make users think twice before using rerender method. I think we shouldn’t have to wait for this one for v4.

I had to use it few times for redux stuff coming from SSR if I remember correctly, so this was the only way to simulate very specific behaviour in the component by updating the store and forcing a rerender.

**Comment by gndelia** [comment]
The rule `prefer-screen-queries` allowed the usage of `rerender` as expected; I just created a PR to add a few tests and reflect it on the docs

**Comment by gndelia** [comment]
I'm taking this for the incoming days
