### ISSUE TITLE
Include `eslint@7` in peer dependency range

### ISSUE THREAD

**Issue by SimenB** [testing-library/eslint-plugin-testing-library#193]
https://github.com/testing-library/eslint-plugin-testing-library/blob/f9f499b38209df0cf42fabcbcaafed1fe15f31a7/package.json#L69-L71

**Comment by nickmccurdy** [comment]
This seems to be a duplicate of #138 and it will be fixed by #139. Mind if I close this?

**Comment by SimenB** [comment]
Ah, didn't find that somehow when searching 👍

**Comment by Belco90** [comment]
This has been finally released in [v3.9.0](https://github.com/testing-library/eslint-plugin-testing-library/releases/tag/v3.9.0) 🎉
