### ISSUE TITLE
New Rule: dont-use-query-selector

### ISSUE THREAD

**Issue by benmonro** [testing-library/eslint-plugin-testing-library#199]
Would be nice to have a rule that can warn if someone uses something other than RTL to make a query (querySelector, getElementById, etc)

**Comment by Belco90** [comment]
I guess you mean this one https://github.com/testing-library/eslint-plugin-testing-library/pull/190 which is planned for v4.

**Comment by gndelia** [comment]
I think #177 solved that... but on second thoughts, I'm not sure is obvious from the name.

**Comment by benmonro** [comment]
ah yeah ok we can close this.  apologies.
