### ISSUE TITLE
refactor node-utils type guards to use the AST_NODE_TYPES enum

### ISSUE THREAD

**Issue by gndelia** [testing-library/eslint-plugin-testing-library#203]
I found this `enum` which contains all the types we've been hardcoding in the type guards in [node-utils.ts](https://github.com/testing-library/eslint-plugin-testing-library/blob/master/lib/node-utils.ts)

![image](https://user-images.githubusercontent.com/352474/88486752-56e1d800-cf56-11ea-8dfa-7a7e66571419.png)

The import for that enum

```ts
import { AST_NODE_TYPES } from '@typescript-eslint/experimental-utils';
```

We should replace all the hardcoded values in each type guard function (`isAwaitExpression`, `isIdentifier`, and so  on) for the corresponding values from that enum

_Originally posted in https://github.com/testing-library/eslint-plugin-testing-library/pull/201#discussion_r460559779_

**Comment by codecog** [comment]
@gndelia will take on this issue

**Comment by codecog** [comment]
https://github.com/testing-library/eslint-plugin-testing-library/pull/205
