### ISSUE TITLE
Check formatting and eslint in CI + review pre-commit hook

### ISSUE THREAD

**Issue by gndelia** [testing-library/eslint-plugin-testing-library#210]
There have been a few PRs that had style modifications in files or Readme examples of code that were no actual changes as part of the PR that was being opened. 

We are not enforcing our defined styling enough (I think it's only run in a `pre-commit` hook) which can be skipped. This ticket is to

- [ ] Review the pre-commit hook to ensure it is actually working, and (except for manual skip by the dev) that it always runs when committing new code

- [ ] Update our CI process to verify the code to be merged is following the eslint and prettier rules, preventing new code from being merged if it does not follow our style guide

**Comment by Belco90** [comment]
I can see already an issue: `.lintstagedrc` is trying to format `.js` files, which we forgot to update to include `.ts` files when we moved the plugin to TS!

Another issue we might have: pre-commit hook in `.huskyrc` is running tests and them lintstage command. This caused me issues in the past as was losing the modified files context after the 1st command was called. Instead, the corresponding config to avoid this would be:

**.huskyrc**
```
{
  "hooks": {
    "pre-commit": "lint-staged", // <-- we just run lint-staged here to make sure we don't lose the staged files context
    "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
  }
}
```

**.lintstagedrc**
```
{
  "*.{js,ts}":[
    "eslint --fix", // <-- first we lint staged files
    "prettier --write", // <-- then we format them
    "jest --findRelatedTests", // <-- now we run tests related to modified files, similar to jest watch mode
    "git add" // <-- git add is still needed in the lint-staged version we use but has been removed recently so we can get rid of it in the future
  ],
  "*.md": ["prettier --write", "git add"]
}
```

**Comment by Belco90** [comment]
Note that I'm not reusing any of our scripts from `package.json`. This is on purpose. [lint-staged allow to run your custom npm scripts](https://github.com/okonet/lint-staged#reuse-npm-script) but you need to pass that final `--` so the script can receive the list of modified files. I prefer to stick to hardcoded eslint, prettier and jest commands as I had problems too by forgetting those final dashes in some of them.

**Comment by gndelia** [comment]
>  git add is still needed in the lint-staged version we use but has been removed recently so we can get rid of it in the future

what about updating the lint-staged version? It's a dev dependency. Or is it anything that might block us?

**Comment by Belco90** [comment]
Updating both husky and lint-staged would be great actually!

**Comment by gndelia** [comment]
ok I think I can probably check it in the incoming days. I'm taking it

**Comment by Belco90** [comment]
I've seen the current repo has lot of ESLint errors, so maybe we can do this over v4 to do this over next changes?

**Comment by gndelia** [comment]
Do you mean to apply the changes directly on v4? Sure I can do that.
