### ISSUE TITLE
feature request: no-await-fire-event

### ISSUE THREAD

**Issue by benmonro** [testing-library/eslint-plugin-testing-library#219]
We accidentally enabled await-fire-event in our react project and discovered that awaiting fireEvent can actually cause tests to be slow and flaky as a result (removing the await fixes it). so was thinking that an opposite rule or even a config option to the await-fire-event to work in opposite mode would be useful

**Comment by Belco90** [comment]
I guess this could be wrapped into a `no-await-sync-utils` to do the opposite than `await-async-utils`. I don't know if there are any other sync util than `fireEvent` that could be included there, but with this approach we can include any new sync util here. What do you think?

**Comment by benmonro** [comment]
Works for me. My only thought would be that you wouldn't want the rules to conflict with each other for vue users but I'm not a cute user so that's not going to affect me. 🙂

**Comment by Belco90** [comment]
I haven't thought about that conflict. Maybe we need to create this rule with a config options for disabling specific methods to be check so Vue users can enable this rule but disabling `fireEvent`.

**Comment by benmonro** [comment]
That would work.
