### ISSUE TITLE
No errors or warnings when use render wrapper

### ISSUE THREAD

**Issue by sshmyg** [testing-library/eslint-plugin-testing-library#246]
Hello, if I use wrapper for render, eslint not shows any warnings (errors).

With wrapper
![image](https://user-images.githubusercontent.com/1410608/97679433-ed65ee00-1a9d-11eb-823c-caed57633e75.png)

Without wrapper
![image](https://user-images.githubusercontent.com/1410608/97679614-28682180-1a9e-11eb-877d-4afa18ef1e50.png)

**Comment by Belco90** [comment]
Hi @sshmyg. Indeed, current version of the plugin is not detecting `render` wrappers properly, causing false negatives or opted-out rules.

However, this is been addressed properly on v4, which we are working at the moment. To handle this case properly we need to refactor and improve how the plugin works internally, and that's what we are doing in that next major version.

If you want to stay up to date with v4 I suggest you to check [issue with all info for v4](https://github.com/testing-library/eslint-plugin-testing-library/issues/186) and [issue for internal refactor + new settings](https://github.com/testing-library/eslint-plugin-testing-library/issues/198) which will solve your mentioned issue.

Apologies for any problem this may have caused.

**Comment by sshmyg** [comment]
@Belco90  Thank you for the quick replay. 🤝
Will wait for v4.

**Comment by Belco90** [comment]
This should be fixed on v4.0.0

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/eslint-plugin-testing-library/v/4.0.0)
- [GitHub release](https://github.com/testing-library/eslint-plugin-testing-library/releases/tag/v4.0.0)
