### ISSUE TITLE
Drop some custom type guards in favor of ASTUtils

### ISSUE THREAD

**Issue by gndelia** [testing-library/eslint-plugin-testing-library#253]
As seen in some PRs created by @Belco90 , there's a utility `ASTUtils` in ` '@typescript-eslint/experimental-utils'` which can replace some, but not all, of the type guards we have in our [node-utils.ts file](https://github.com/testing-library/eslint-plugin-testing-library/blob/master/lib/node-utils.ts)

This ticket is to review which type guards (`isIdentifier`, `isVariableDeclarator`, etc) are repeated, and drop those in favour of the ones in `ASTUtils`. The ones that are not available there should continue to exist with our custom implementation.

Edit: This PR should target the v4 branch

**Comment by Belco90** [comment]
Ideally, this should be done on v4 so we get rid of it everywhere 😅

**Comment by thomlom** [comment]
Is someone already working on it? I haven't contributed to the codebase for a while and I'd like to get familiar with it again. I think that issue may be the best to start with 🙂
