### ISSUE TITLE
prefer-user-event should consider the use case where fireEvent is used as a function

### ISSUE THREAD

**Issue by gndelia** [testing-library/eslint-plugin-testing-library#261]
In addition to the method events like `fireEvent.click`, it is also possible to create custom events objects and use `fireEvent` as a function, as [the documentation for fireEvent shows](https://testing-library.com/docs/dom-testing-library/api-events/#createeventeventname)

```js
// form 1
const myEvent = createEvent.click(node)
fireEvent(node, myEvent)

// form 2
fireEvent(
  input,
  createEvent('click', input)
)
```

The rule should recommend to use `userEvent.click()` 

the rule should consider this form too

**Note**: This rule has been migrated in the `v4` branch, so anyone taking this issue should do so starting from branch `v4` (And targeting it as well)

**Comment by Belco90** [comment]
This one must wait until v4 is released.

**Comment by gndelia** [comment]
now that v4 is released, we can tackle this one. I think I can tackle it the next week, so if no one takes it during that time, I might do so

**Comment by gndelia** [comment]
I'm taking this one so stale bot doesn't close it 😆  I'll tackle it during the week
