### ISSUE TITLE
New rule: Disallow queryBy* queries?

### ISSUE THREAD

**Issue by tom-sherman** [testing-library/eslint-plugin-testing-library#262]
The "[Which query should I use](https://testing-library.com/docs/guide-which-query/)" doc doesn't mention them and I seem to remember @kentcdodds mentioning that queryBy* queries ideally wouldn't be in the library and are only there for backwards compatibility reasons.

**Comment by Belco90** [comment]
Hello @tom-sherman. First time I heard about queryBy* being deprecated. It's used for [asserting elements disappearsnce](https://testing-library.com/docs/guide-disappearance/#asserting-elements-are-not-present) so I would need corresponding resource for going ahead with this rule.

**Comment by tom-sherman** [comment]
Definitely not a deprecation from what I've heard, just a recommendation against - and I'd like to be able to enforce this recommendation with a lint rule.

> It's used for asserting elements disappearsnce

getBy* queries can be used for this too right?

```javascript
expect(() => getByTest("click me")).toThrow()
```

It's not as ergonomic though - my general use case is to have a banlist of queries. Such a feature would allow me to ban queryBy* calls while keeping this library unopinionated on the matter.

**Comment by Belco90** [comment]
That use case is right but not ideal. The actual use case for queryBy is checking elements are not present. I think [this rule](https://github.com/testing-library/eslint-plugin-testing-library/blob/master/docs/rules/prefer-presence-queries.md) should help you to report getBy and queryBy used for intended presence assertion.

**Comment by tom-sherman** [comment]
Yup, that's exactly what I'm looking for - thanks!
