### ISSUE TITLE
Transfer to testing library org on GitHub. 

### ISSUE THREAD

**Issue by benmonro** [testing-library/eslint-plugin-testing-library#27]
Love this plugin.  If you guys are interested we can transfer it over to the testing library org on GitHub.  This would give the plugin a lot of visibility and maybe spur more contributions.  I did this for the testcafe-testing-library I wrote and it definitely helped.  Up to you of course.

**Comment by Belco90** [comment]
Yes, I already discussed this with Kent! In the original issue https://github.com/testing-library/dom-testing-library/issues/345 I mentioned I prefer to have it in my repo for a while until the plugin is mature itself (couple of things related to CI, docs and guidelines have to be improved), and after that I'll consider transferring the plugin to testing library org definitely.

**Comment by Belco90** [comment]
I just remembered another reason for not transferring the plugin at the moment also commented in the original issue: avoiding scoped package. [It's definitely allowed by ESLint](https://eslint.org/docs/developer-guide/working-with-plugins) but not really adopted yet and it doesn't seem like a standard for their plugins so everyone is looking for these plugins as `eslint-plugin-*` rather than `@*/eslint-plugin`

**Comment by benmonro** [comment]
you wouldn't have to make it a scoped package just because it's in the github org.  Actually, i think most folks (myself included) would prefer it that way.    Anyway, up to you guys, but cool, glad Kent brought it up.

**Comment by benmonro** [comment]
regarding docs, it would be really great to have them in the `testing-library.com` docs, though personally I think the docs are fine.

**Comment by Belco90** [comment]
Good point about the scoped package, something less to be worried about then.

About the doc: I'm not really sure about having that in a different project as it feels completely attached to the development of the rules themselves and I would like to include danger JS to help contributors not forgetting about adding/updating corresponding doc when adding new rules or updating existing ones. I found this way more useful, but I don't know if there is a way of combining this by extracting the doc out.

**Comment by benmonro** [comment]
yeah actually after posting that i noticed there's a link from there to here anyway for the docs, so all good.  any way kudos for starting this. 👍

**Comment by thomlom** [comment]
I think bringing this repo to the org would be great too! I think it would help in increasing its visibility and it would make it more "official". But that's just my two cents 🙂

**Comment by benmonro** [comment]
@Belco90 you should totally move this over.  I think you would get more contributors.  The issues you mentioned can still be worked on after it transfers and you'll still be the owner.  I would love to see this plugin get more adoption and then more contributions.

**Comment by Belco90** [comment]
Not worried about losing the ownership to be honest, just leaving everything in good place before transferring it. Everything related to semantic release and all contributors is set up. I'm finishing a proposal for CONTRIBUTING guidelines and issue templates. After that (which I'm closed to finish) I'll probably transfer it.

**Comment by bcarroll22** [comment]
I agree, I think it'd be really nice to have this moved over! I just now saw this, I never even knew it existed. 

Kinda related, I think all of these rules work for React Native as well, including the one where you shouldn't import from DOM Testing Library (lol kinda obvious in RN though).

**Comment by Belco90** [comment]
Hey all! Sorry about not giving you any update about this. My idea is to go back to this in Christmas and then transferring this to testing-library organization for sure when I have some spare time.

**Comment by thomlom** [comment]
Any updates on this issue @Belco90 ? 🙂

**Comment by Belco90** [comment]
Yes sorry! I created an issue for it here https://github.com/testing-library/dom-testing-library/issues/424 (same repo were I opened rhe original issue for the eslint plugin, didn’t find a better place) but didn’t get any update yet.

**Comment by kentcdodds** [comment]
I've added you to the org. You should be able to transfer this repo to the org now.

Thanks everyone!
