### ISSUE TITLE
Move release flow from travis to github actions

### ISSUE THREAD

**Issue by MatanBobi** [testing-library/eslint-plugin-testing-library#275]
Following [this](https://github.com/testing-library/dom-testing-library/pull/809#issue-515554670) PR by @kentcdodds, we're migrating all travis pipelines to github actions :)

An example for the action can be seen [here](https://github.com/testing-library/dom-testing-library/blob/master/.github/workflows/validate.yml).

**Comment by Belco90** [comment]
Hello Matan! Indeed, we should do this asap. Thanks for pointing to an existing PR doing this migration 💯 . I'm not sure if I'll address this on default branch or future v4 since it's close to be released and the CI config was updated there.

**Comment by gndelia** [comment]
I'd suggest applying this change in the v4 directly, as just like you mentioned, there have been changes, and I guess if any changes arrive at master (lately all changes have been arriving at v4 directly), we could still use travis for those scenarios
