### ISSUE TITLE
New rule: no-log-testing-playground-url

### ISSUE THREAD

**Issue by MichaelDeBoey** [testing-library/eslint-plugin-testing-library#294]
Just like `no-debug` but for `screen.logTestingPlaygroundURL()`

Reference: https://github.com/testing-library/dom-testing-library/pull/781

**Comment by Belco90** [comment]
It sounds like a good idea, and would be really easy to implement just mirroring the same checks from `no-debug`. However, we have to put it on hold until v4 gets released or it will take forever!

**Comment by MichaelDeBoey** [comment]
I think we can indeed extract a lot of the `no-debug` code in order to implement this one

**Comment by Belco90** [comment]
Rethinking this suggestion: I think `no-debug` should report `logTestingPlaygroundURL` usages. Both `debug` and `logTestingPlaygroundURL` are debugging utils, so `no-debug` should take care of them. Even `prettyDOM` and `logRoles` probably.

**Comment by MichaelDeBoey** [comment]
Maybe we should rename `no-debug` to something like `no-debugging-utils`?

We can create that new rule in a minor release and let that handle all of them (`debug`/`screen.debug`, `screen.logTestingPlaygroundURL`, `prettyDOM`, `logRoles`, `logDOM`, `prettyFormat`, ...).

We can deprecate the `no-debug` rule for now and maybe throw a warning or so to say that using the new `no-debugging-utils` should be used and remove it in v5?
Or we can update `no-debug` and rename it to a better suiting name in v5 too if we want?

**Comment by MichaelDeBoey** [comment]
On the other hand, maybe some people will want to enable this behavior for some utils, but not for others.
So having a setting for which one to enable can be helpful too I think

**Comment by Belco90** [comment]
- I would implement everything under `no-debug` and rename it in a future v5 if necessary.
- The rule should accept an option to decide which debug utils are allowed like [`no-console` ESLint one](https://eslint.org/docs/rules/no-console#disallow-the-use-of-console-no-console)

**Comment by MichaelDeBoey** [comment]
Sounds like a solid plan @Belco90! 👊

**Comment by MichaelDeBoey** [comment]
Since it's a breaking change to error on these new functions, we should set the default of the `allow` option to be `['debug', 'screen.debug']`

Only in v5 we can update it to default to all functions then. 🤔

**Comment by Belco90** [comment]
Putting ESLint errors in that way, every single change should be a breaking change since it could potentially report errors not reported before. I'm never sure what to do in this case. If you take a look at [ESLint releases](https://eslint.org/blog/), they seem to include this sort of changes in a minor and leave major for purely API changes, dependency updates, or config changes.

Anyway, setting it to `'debug'` by default shouldn't be a problem (`screen.debug` shouldn't be an option tho, it's just another way of using `debug` from Testing Library and that's already addressed in v4 of the plugin across all rules).

**Comment by MichaelDeBoey** [comment]
If ESLint makes these kind of things a minor, I think we should do that too

**Comment by gndelia** [comment]
> * I would implement everything under `no-debug` and rename it in a future v5 if necessary.
> * The rule should accept an option to decide which debug utils are allowed like [`no-console` ESLint one](https://eslint.org/docs/rules/no-console#disallow-the-use-of-console-no-console)

I like this plan - but I think definitely `no-debug` has to be renamed as it might be confusing as it is

**Comment by Belco90** [comment]
Closing this ticket and adding the renaming to [the list of things to do on the next major](https://github.com/testing-library/eslint-plugin-testing-library/discussions/376).
