### ISSUE TITLE
[v4] Crash `Cannot read property 'name' of null` in detect-testing-library-utils getImportedUtilSpecifier

### ISSUE THREAD

**Issue by epmatsw** [testing-library/eslint-plugin-testing-library#305]
One of our tests has some code that looks like:

```ts
(window as any).__THING = false;
```

This is causing a crash with `Cannot read property 'name' of null`.

Looking at [`getImportedUtilSpecifier`](https://github.com/testing-library/eslint-plugin-testing-library/blob/82ace4946fca958698adcc367ba3e8fa9ab070a4/lib/detect-testing-library-utils.ts#L604-L611), it calls `getPropertyIdentifierNode` and checks `.name` on it, even though that [can return `null`](https://github.com/testing-library/eslint-plugin-testing-library/blob/82ace4946fca958698adcc367ba3e8fa9ab070a4/lib/node-utils.ts#L401). It looks like the root cause might be `isExpressionStatement` not handling `TSAsExpression` types.

**Comment by Belco90** [comment]
Hey @epmatsw, thank you very much for your feedback on v4! This is a tricky one, but thank you very much for the detailed explanation. Added to the list of things to fix.
