### ISSUE TITLE
[v4][no-debug] Crash with `Cannot read property 'name' of null`

### ISSUE THREAD

**Issue by epmatsw** [testing-library/eslint-plugin-testing-library#306]
We've got some code that looks like:

```js
thing.method.lastCall.args[0]();
```

This is causing a crash in the CallExpression handler in `no-debug`. In this case, `callExpressionIdentifier` is null. I suspect that `getDeepestIdentifierNode` doesn't handle array accessors correctly, and it also [can explicitly return `null`](https://github.com/testing-library/eslint-plugin-testing-library/blob/beta/lib/node-utils.ts#L433).

**Comment by Belco90** [comment]
Hey @epmatsw, thank you very much for your feedback on v4! This is a tricky one, but thank you very much for the detailed explanation. Added to the list of things to fix, I think this will be related to #305
