### ISSUE TITLE
First round of v4 beta issues

### ISSUE THREAD

**Issue by Belco90** [testing-library/eslint-plugin-testing-library#307]
The first round of issues I found while testing v4 beta:

- problem A: `await-async-utils` doesn't report the right node name
  <img width="649" alt="CleanShot 2021-03-28 at 20 54 18@2x" src="https://user-images.githubusercontent.com/2677072/112891715-c22d0c80-90d8-11eb-9775-bd69726145d5.png">
- problem B: `prefer-find-by` is reporting an incorrect message
  <img width="492" alt="CleanShot 2021-03-28 at 21 24 41@2x" src="https://user-images.githubusercontent.com/2677072/112891897-f6083200-90d8-11eb-979e-08c1aed216e8.png">
- problem C: `no-await-sync-query` reports an error when a parent is awaited (related to #304 )
  <img width="635" alt="CleanShot 2021-03-28 at 20 55 14@2x" src="https://user-images.githubusercontent.com/2677072/112891961-0b7d5c00-90d9-11eb-9a2e-ae7c04a1445f.png">
- problem D: `no-wait-for-multiple-assertions` should display the error on each assertion other than the first one instead of a single error on `waitFor`
- problem E: `no-wait-for-side-effects` should display the error on each side effect instead of a single error on `waitFor`
- ~~problem F: ESLint `peerDependency` seems set incorrectly~~ this is actually fine, it seems a warning due to installing it through `resolutions` and ESLint being a sub-dependency of `react-scripts`
  ![CleanShot 2021-03-29 at 21 54 25@2x](https://user-images.githubusercontent.com/2677072/112892382-847cb380-90d9-11eb-9e14-74f427015324.png)

**Comment by gndelia** [comment]
👏  nice work here!
Question, what's the expected message in the `prefer-find-by` error? Do you expect the full `prefer screen.findByRole('button',  { name: /submit/i })` ?

**Comment by Belco90** [comment]
@gndelia the error should say just "use `findByRole` instead of `waitFor` + `getByRole`, so it's something simple. Otherwise we pollute the output with a lot of code.
