### ISSUE TITLE
Allow multiple utils modules on Shared Settings

### ISSUE THREAD

**Issue by Belco90** [testing-library/eslint-plugin-testing-library#315]
It would be interesting to allow `"testing-library/utils-module"` to support multiple modules. For doing so:
- [ ] `"testing-library/utils-module"` should expect an array of strings
- [ ] all tests cases setting `"testing-library/utils-module"` must be updated
- [ ] add new test cases in fake rule to test several `"testing-library/utils-module"` set
- [ ] update `isAggressiveModuleReportingEnabled` to check array length is greater than 0
- [ ] update `detectionInstructions` to check if some of the utils modules end with corresponding string.
- [ ] update migrating guide to reflect this change

> This example makes it seem like this can only be a single string and not an array? Not sure if it'd add too much complexity to support multiple utils modules.
> 
> For example a user could have many custom selectors each imported from a different module. Probably not common, but just calling it out.
> 
> _Originally posted by @CreativeTechGuy in https://github.com/testing-library/eslint-plugin-testing-library/pull/312#r606961346_

**Comment by Belco90** [comment]
@CreativeTechGuy ok so I've been trying to implement the first approach for this but it's not so easy as I thought. Apart from changes mentioned in the description, all checks around custom test utils should be updated to look for specifiers on an array rather than a single string.

The plugin is not ready for this, since it assumes it will have a single import, not several of them. This implies a lot of work, including corresponding tests to make sure different cases with several imports work as expected.

For this reason, I think it's better to leave this as a future improvement for a 4.X release.

**Comment by CreativeTechGuy** [comment]
Wow thank you for spending so much time on this suggestion. But I definitely agree, we should wait and see if there's any demand for it since it's a non-trivial change.

**Comment by Belco90** [comment]
No problem. I thought it would be a quick win, but it's not. I'm gonna close the ticket but reference it in v4 issue as a future improvement.

**Comment by rosczja** [comment]
I would definitely like to have this feature, but I understand that this is not trival to implement.

We have two different types of tests: unit and integration. Both use a different custom render function and re-export testing-library stuff. Each type has its own module.
