### ISSUE TITLE
Constant error testing-library/no-node-access

### ISSUE THREAD

**Issue by DavidHenri008** [testing-library/eslint-plugin-testing-library#333]
I updated to the latest v4 version (4.0.0) and since then I am always getting the ```testing-library/no-node-access``` error. 
When I say always I really mean **always**, I tried the following and no matter what I still get the error:
- I downgraded back to version 3.10.2,
- I removed ```eslint-plugin-testing-library``` from my config,
- I uninstalled ```eslint-plugin-testing-library```,
- I erased my ```yarn.lock``` and my ```node_modules```, and then re-installed,
- I rebooted my PC.

Here is my config:
```
extends: ['airbnb', 'plugin:prettier/recommended', 'plugin:testing-library/react'],
plugins: ['react-hooks', 'testing-library'],
parser: 'babel-eslint',
env: {
  browser: true,
  commonjs: true,
  es6: true,
  jest: true,
  serviceworker: true,
},
rules: {
  'testing-library/no-node-access': 'off',
  // Console are often use during development.
  'no-console': 'off',
}
```

Am I crazy?  The only explanation is if this error comes from a different package...

I thought the ```testing-library/no-node-access``` was only introduced in v4.

I really need some help.

**Comment by DavidHenri008** [comment]
If someone encounters this, I was able to solve the issue by:
- deleting my whole git folder on my PC and
- cloning again the repository.

**Comment by Belco90** [comment]
Oh wow, I haven't run into something like this before. When I had similar issues, it only happened in the IDE and restarting it did the trick.

**Comment by DavidHenri008** [comment]
After more investigation I found the following:

My webpack configuration uses the loader eslint-loader to run the eslint verification on my code before the build step (like in CRA). This module creates a cache folder in the ```node_modules``` of my lerna package and for an unknown reason, it was caching the configuration even if I was changing it. This is why erasing the whole git folder solved my issue. A simple cleanup of the ```.cache``` folder is enough to fix the issue.

**Comment by Belco90** [comment]
TIL, thanks for the explanation!
