### ISSUE TITLE
`render-result-naming-convention` false positives for any `render*` named fn

### ISSUE THREAD

**Issue by ljosberinn** [testing-library/eslint-plugin-testing-library#337]
Apparently `render-result-naming-convention` just checks whether _any_ function or method beginning with `render` is called within any test file.

The following lines are reported as false positives:
https://github.com/ljosberinn/personal-react-boilerplate/blob/master/src/client/__tests__/_document.test.tsx#L61
https://github.com/ljosberinn/personal-react-boilerplate/blob/master/src/client/__tests__/_document.test.tsx#L80

![image](https://user-images.githubusercontent.com/29307652/114587368-e286ca80-9c85-11eb-9a16-13175e5d4b2f.png)

However, these are not methods exposed through `render` or some custom `render` through `@testing-library/*`.

**Comment by Belco90** [comment]
Hey Gerrit! As per [Aggressive Reporting - Renders mechanism](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/migrating-to-v4-guide.md#renders), by default all methods containing `*render*` will be assumed as a reportable render. Additionally, as per [Aggressive Reporting - Imports mechanism](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/migrating-to-v4-guide.md#imports), any module by default will be assumed as a valid Testing Library one: in other words, it doesn't matter from where it's imported.

You can restrict both mechanisms using [Shared Settings](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/migrating-to-v4-guide.md#shared-settings) so you can indicate your custom module (if any) to restrict the valid imports, and your custom renders (if any) to restrict the reportable renders.

We are working on extending the Shared Settings so you can switch those mechanisms entirely off without setting any particular custom render or module. You can follow the progress on this in #335.

I hope this helps you to fix those false positives.

**Comment by ljosberinn** [comment]
Thank you, I extended my config [to automatically detect those](https://github.com/ljosberinn/eslint-config-galex/blob/master/src/overrides/jest.js#L808) at least :)
