### ISSUE TITLE
Multiple utils-module for several test types

### ISSUE THREAD

**Issue by Belco90** [testing-library/eslint-plugin-testing-library#348]
> I would definitely like to have this feature, but I understand that this is not trival to implement.
> 
> We have two different types of tests: unit and integration. Both use a different custom render function and re-export testing-library stuff. Each type has its own module.

_Originally posted by @rosczja in https://github.com/testing-library/eslint-plugin-testing-library/issues/315#issuecomment-823006049_

**Comment by Belco90** [comment]
Hey @rosczja! I'm moving here your petition for allowing to set a list of modules into `utils-module`.

This is a feature that will take time to implement and won't happen soon to be honest. However, I'd like you to give us more info about your setup since it might be possible for you to achieve what you want with the current plugin version + ESLint `overrides`.

Can you share more details about how you differentiate between those two types of tests? Do they have different filename suffix? Or perhaps are located under different folders?

**Comment by rosczja** [comment]
Hey @Belco90 , thank you very much.

Yes, we differentiate between those two types by filename suffix. So you are right, I could try to use `overrides`. Will definitely try this out.

**Comment by Belco90** [comment]
Alright. Assuming you use `.unit` and `.integration` suffixes for differentiate them, you could do something like this:

```javascript
// .eslintrc
{
  "plugins": [/* other plugins */, "testing-library"],
  "extends": [/* other extends */, "plugin:testing-library/react"],

  "overrides": [
    {
      // unit tests
      "files": ["**/?(*.)+(spec|test).unit.[jt]s?(x)"],
      settings: {
        "testing-library/utils-module": "unit-test-utils"
      }
    },
    {
      // integration tests
      "files": ["**/?(*.)+(spec|test).integration.[jt]s?(x)"],
      settings: {
        "testing-library/utils-module": "integration-test-utils"
      }
    }
  ],
};
```

However, if you have your tests files identified properly, I'd leave the new Aggressive Reporting doing its thing and [run `eslint-plugin-testing-library` only against your test files](https://github.com/testing-library/eslint-plugin-testing-library#run-the-plugin-only-against-test-files) (no matter if unit or integration).

Let me know if any of these options work for you!

**Comment by gndelia** [comment]
@Belco90 I've seen this kind of snippet mentioned a couple of times (About using the file extension to separate files); Maybe it's worth documenting somewhere (like a FAQ or as part of the readme)

**Comment by Belco90** [comment]
@gndelia we added it to our README!

- [Run the plugin only against test files](https://github.com/testing-library/eslint-plugin-testing-library#run-the-plugin-only-against-test-files)
- [Troubleshooting](https://github.com/testing-library/eslint-plugin-testing-library#troubleshooting)

**Comment by gndelia** [comment]
🤦‍♂️ for me

**Comment by rosczja** [comment]
Hi @Belco90 , thanks again. Works for me, too.

**Comment by Belco90** [comment]
@rosczja I'm glad it works! I'm closing the issue then.
