### ISSUE TITLE
`no-wait-for-empty-callback`: report empty `Promise.resolve()`

### ISSUE THREAD

**Issue by MichaelDeBoey** [testing-library/eslint-plugin-testing-library#370]
I think that `await waitFor(() => Promise.resolve())` should be reported by `no-wait-for-empty-callback` too.

I know @kentcdodds [showed an alternative to wait for a mocked promise](https://kentcdodds.com/blog/fix-the-not-wrapped-in-act-warning#an-alternative-waiting-for-the-mocked-promise) and in theory we could rewrite the `act(() => promise)` call in his example as `await waitFor(() => promise)`.

This example is only valid because there's no visual feedback to wait for, but most of the times there is.

My proposition is to also report an empty `Promise.resolve()` and people could disable the rule deliberately when it's not possible to wait for visual feedback.

**Comment by kentcdodds** [comment]
Agreed

**Comment by Semigradsky** [comment]
`no-wait-for-empty-callback` was removed in v6. Should it be closed?

**Comment by Belco90** [comment]
@Semigradsky Good catch! Thanks for pointing it out.
