### ISSUE TITLE
Slip in eslint --fix rule for `jest-dom/prefer-to-have-style`

### ISSUE THREAD

**Issue by johan** [testing-library/eslint-plugin-testing-library#375]
With `eslint --fix`, this code:
```js
expect(screen.getByRole("alert").getAttribute("inert")).toBe("");
```
should auto-correct to:
```js
expect(screen.getByRole("alert")).toHaveAttribute("inert");
```
…but currently auto-corrects to the opposite:
```js
expect(screen.getByRole("alert")).not.toHaveAttribute("inert");
```

(The current behaviour is correct for values `null` and `undefined`; I'd expect there's a falsey-ness slip, somewhere.)

**Comment by Belco90** [comment]
Hey @johan! I'm sorry but this is the repo for `eslint-plugin-testing-library`, but the rule you have issues with is `eslint-plugin-jest-dom`. You need to [report the issue in that repo](https://github.com/testing-library/eslint-plugin-jest-dom/issues/new).

**Comment by MichaelDeBoey** [comment]
@johan I even think this is the expected behavior tbh as you're checking for an empty string as value of an attribute, so that's the same as not having the attribute.

**Comment by johan** [comment]
🥂 Thanks for the redirection and sorry about the noise! 🤠
