### ISSUE TITLE
`no-unnecessary-act`: option for strict reporting

### ISSUE THREAD

**Issue by Belco90** [testing-library/eslint-plugin-testing-library#382]
Since the current implementation of `no-unnecessary-act` doesn't report `act` usages with react-testing-library calls inside if mixed with non-react-testing-library, it would be interesting to add a new `isStrict` option (`false` by default) which makes the rule to always report react-testing-library calls inside `act` no matter if mixed with non-react-testing-library.

**Comment by Belco90** [comment]
@zaicevas this is the issue I mentioned to tackle the strict reporting in `no-unnecessary-act`.

**Comment by zaicevas** [comment]
@Belco90 do you mind if I'll try to implement it?

**Comment by Belco90** [comment]
> @Belco90 do you mind if I'll try to implement it?

By all means! I won't have much spare time during summer, so I'd really appreciate if you can take care of this one.
