### ISSUE TITLE
New rule: reporting `getBy*` inside `waitForElementToBeRemoved`

### ISSUE THREAD

**Issue by zaicevas** [testing-library/eslint-plugin-testing-library#399]
[Docs](https://testing-library.com/docs/guide-disappearance#waiting-for-disappearance) use `queryBy*` in examples of waiting for disappearance. AFAICS one could use either `getBy` or `queryBy` and both would work with `waitForElementToBeRemoved`. However, different error messages are displayed if the element is initially not present:

```
      // TestingLibraryElementError: Unable to find an element by: [data-testid="loader"]
      await waitForElementToBeRemoved(screen.getByTestId('loader'))

      // The element(s) given to waitForElementToBeRemoved are already removed. 
      // waitForElementToBeRemoved requires that the element(s) exist(s) before waiting for removal.
      await waitForElementToBeRemoved(screen.queryByTestId('loader'))
```

The error message when using `queryBy` is more descriptive. Additionally, it might be useful for the users to keep consistency in the codebase by using either `queryBy` or `getBy` when asserting disappearance.
**Therefore, we could have a new rule that would force using `queryBy` inside `waitForElementToBeRemoved`.**

**Comment by Belco90** [comment]
Hey @zaicevas! This looks like a nice proposal for a new rule. I guess it could be named `prefer-wait-for-removed-query` or something similar (I don't have anything better in mind).

Would you like to work on this?

**Comment by zaicevas** [comment]
> Would you like to work on this?

I'll take a look at it this weekend and evaluate how big of an effort it is going to be.

**Comment by zaicevas** [comment]
Yes, I'll work on it. I've already started implementing the new rule.

Regarding the name - what about `prefer-query-by-disappearance` ?

**Comment by Belco90** [comment]
> Regarding the name - what about `prefer-query-by-disappearance` ?

I like that name! 🚀
