### ISSUE TITLE
Add template for Pull Requests

### ISSUE THREAD

**Issue by Belco90** [testing-library/eslint-plugin-testing-library#400]
Add template for Pull Requests so:

- user can follow some guidelines to fill in the details about the PR
- flag and track necessary checks have been addressed

Necessary checkbox to track necessary checks are:
- Rules list has been regenerated if any rule has been created/updated/removed (as discussed in https://github.com/testing-library/eslint-plugin-testing-library/issues/397#issuecomment-869732771)

**Comment by MichaelDeBoey** [comment]
This one can be interesting too 👀
https://github.blog/2021-07-13-whats-new-github-changelog-june-2021/#github-issues

**Comment by Belco90** [comment]
Yes! I asked beta access to it but still nothing. I'll enable it as soon as we have it.

**Comment by HonkingGoose** [comment]
> Yes! I asked beta access to it but still nothing. I'll enable it as soon as we have it.

The Issue Forms feature is available for all public repositories, so you don't have to wait for anything. 😉 

The new Forms feature is **not available** for pull requests, sadly....

---

I can make a bug report Issue Form and create a basic pull request template, if you want.
I do need a lot more information from the maintainers before I can start building the form/template. 😉

## Questions about bug report form

- [ ] What information must a bug reporter provide (operating system, npm version, node version, things like that)
- [ ] Do we need a field for error messages/log output, things like that?
- [ ] What input fields are **required**  for a complete bug report?
- [ ] What input fields are **optional** when filling in a bug report?
- [ ] Anything else I need to know before I can start?

## Questions about pull request template

- [ ] Specify what the guidelines are to fill in details about the PR?
- [ ] Flag and track necessary checks are addressed (which checks, specify!)
- [ ] Do we want to remind contributor to use `Fixes #1` to close the linked issue automatically?
- [ ] Anything else I need to know before I can start?

**Comment by Belco90** [comment]
> > Yes! I asked beta access to it but still nothing. I'll enable it as soon as we have it.
> 
> The Issue Forms feature is available for all public repositories, so you don't have to wait for anything. 😉

You are right, I confused myself with the new issues board 🤦‍♂️ . The issue form is available for sure since we used it in Octoclairvoyant.

---

In order to report bugs (and also for new feature issue form), the idea would be to have something similar to ESLint one but simplified. Let me answer those questions!

**What information must a bug reporter provide (operating system, npm version, node version, things like that)**

From the user environment, we need:
* Plugin Version
* ESLint Version
* Node Version
* npm/yarn Version
* Operating System

**Do we need a field for error messages/log output, things like that?**

Yes, ideally the error output or a screenshot in case it's a false positive or something like that. Here would be nice to indicate what the user expected to happen and what actually happens.

**What input fields are required for a complete bug report?**

We would need to know:
* ESLint config
* Rule(s) affected
* the user is willing to submit a pull request to fix this bug

**What input fields are optional when filling in a bug report?**
I guess we can leave an additional textbox for the user so they can add extra info if needed.

**Anything else I need to know before I can start?**
* It should set the `bug` label
* Ideally we would have other issue forms to propose a new rule, to request a rule change, or to request a general change.

---

About PR template:

**Specify what the guidelines are to fill in details about the PR?**
I'm not sure we need this, I think we can skip it for now.

**Flag and track necessary checks are addressed (which checks, specify!)**
- I have read the contributing guidelines (with a link to them)
- If some rule is added/updated/removed, I've regenerated the rules list
- if some rule meta info is changed, I've regenerated the plugin shared configs

**Do we want to remind contributor to use Fixes #1 to close the linked issue automatically?**
Yes, we want to link to the original issue if possible.

**Anything else I need to know before I can start?**

I think that's all really

---

Thank you very much @HonkingGoose!

**Comment by HonkingGoose** [comment]
I think we still want forms for:

- [ ] propose a new rule
- [ ] request a rule change
- [ ] request a general change

@Belco90 Can you explain the requirements for these forms?

**Comment by Belco90** [comment]
I've moved those remaining issue forms to #430 so we can close this one. Thanks @HonkingGoose!
