### ISSUE TITLE
Add remaining issue forms

### ISSUE THREAD

**Issue by Belco90** [testing-library/eslint-plugin-testing-library#430]
Moving remaining issue forms from https://github.com/testing-library/eslint-plugin-testing-library/issues/400#issuecomment-884778671 to this issue.

We still want issue forms for:

- [x] Propose a new rule
- [x] Request a rule change
- [x] Request a general change

Here are the details I think we need from each (heavily inspired from ESLint ones):

### Propose a new rule
Labels: `new rule`
Fields:
- What is the name suggested for this new rule? (required)
- Please describe what the rule should do (required)
- What Testing Library feature does this rule relate to? (required)
- What Testing Library frameworks does this rule relate to? (required)
- What category of the rule is this? (required) Select with the following options
  - Warns about a potential error
  - Suggests an alternate way of doing something
  - Other (please specify in the optional textbox at the end)
- Provide 2-3 code examples that this rule will warn about (required)
- Anything else? (optional)
- Are you willing to submit a pull request to implement this rule? (required) Select with the same options as "Do you want to submit a pull request to fix this bug?" from bug template

### Request a rule change
Labels: `enhancement`
Fields:
- What rule do you want to change? (required)
- Does this change cause the rule to produce more or fewer warnings? (required) Select with "more" and "fewer" options
- How will the change be implemented? (New option, new default behavior, etc.)? (required) Free text input rather than select
- Please provide some example code that this change will affect (required)
- What does the rule currently do for this code? (required)
- What will the rule do after it's changed? (required)
- Anything else? (optional)
- Are you willing to submit a pull request to implement this change? (required) Select with the same options as "Do you want to submit a pull request to fix this bug?" from bug template

### Request a general change
Labels: `enhancement` 
Fields:
- What version of `eslint-plugin-testing-library` are you using? (required)
- What problem do you want to solve? (required)
- Your take on the correct solution to the problem? (required)
- Anything else? (optional)
- Are you willing to submit a pull request to implement this change? (required) Select with the same options as "Do you want to submit a pull request to fix this bug?" from bug template

**Comment by HonkingGoose** [comment]
@Belco90 Is this ready for me to start work on, or do you want to discuss this with your team first?

**Comment by Belco90** [comment]
> @Belco90 Is this ready for me to start work on, or do you want to discuss this with your team first?

Let's see what @MichaelDeBoey and @gndelia think about it!

**Comment by MichaelDeBoey** [comment]
Looks good to me! 👍

**Comment by Belco90** [comment]
I think we are good to go, and we can update the forms later if @gndelia has some feedback.

**Comment by HonkingGoose** [comment]
We now have PRs for all 3 forms. 😉

**Comment by Belco90** [comment]
All sorted now, thank you very much for your contribution @HonkingGoose!

**Comment by Belco90** [comment]
@all-contributors please add @HonkingGoose for maintenance

**Comment by HonkingGoose** [comment]
> All sorted now, thank you very much for your contribution @HonkingGoose!

You're welcome! 😄
