### ISSUE TITLE
Support ESLint 8.x

### ISSUE THREAD

**Issue by MichaelDeBoey** [testing-library/eslint-plugin-testing-library#462]
ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉

This version contains a number of breaking changes which will prevent our tooling from working at all with it.

This project is maintained by volunteers. Support will be added as time permits.

If you're not willing or able to help with adding support:

- Please do not raise issues.
- Please do not comment on threads.
- Please be patient and subscribe to this issue for updates.

This update will require breaking changes on our side as well, so it will take some time to support it.
There is no ETA on this work. Again _please be patient_.

---

✅  = done
🕐  = in progress
🔲  = not yet started

# Breaking changes in ESLint 8.X

## ✅   Drop node v10/v13/v15

Refs: https://github.com/eslint/eslint/issues/14023, https://github.com/eslint/eslint/pull/14592, https://github.com/typescript-eslint/typescript-eslint/pull/3767

We will want to update our node ranges as appropriate.

- [x] https://github.com/testing-library/eslint-plugin-testing-library/pull/463

## 🕐  Remove meta.docs.category in core rules

Refs: https://github.com/eslint/eslint/issues/13398, https://github.com/eslint/eslint/pull/14594

We will want to remove this from the rules

- [x] https://github.com/testing-library/eslint-plugin-testing-library/pull/465

## ✅  Changes with no impact

- Strict package exports
- Disallow `SourceCode#getComments()` in `RuleTester`
- Fixable disable directives
- Require `meta` for fixable rules
- Require `meta.hasSuggestions` for rules with suggestions
- Allow all directives in line comments
- Support new regex `d` flag
- Fix `comma-dangle` schema
- Upgrade `espree` and support new class features
- Add some rules to `eslint:recommended`
- Drop `codeframe` and `table` formatters
- Disallow reserved words in ES3

**Comment by Belco90** [comment]
Nice job @MichaelDeBoey! I've pinned this issue so other people can track ESLint v8 progress easier.
