### ISSUE TITLE
Breaking changes for next v5

### ISSUE THREAD

**Issue by Belco90** [testing-library/eslint-plugin-testing-library#478]
I have a couple of breaking changes I think we should introduce in the new major version taking advantage of having to support ESLint 8

This project is maintained by volunteers. Support will be added as time permits.

If you're not willing or able to help with adding support:

- Please do not raise issues.
- Please do not comment on threads.
- Please be patient and subscribe to this issue for updates.

This update will require breaking changes on our side as well, so it will take some time to support it.
There is no ETA on this work. Again _please be patient_.

---

✅ = done
🕐 = in progress
🔲 = not yet started

### ✅ `no-render-in-setup`

Enable for `angular`, `react` & `vue` configs (`dom` doesn't have a render method)

- [x] https://github.com/testing-library/eslint-plugin-testing-library/pull/481

### ✅ `no-unnecessary-act`

Enable for `react` configs

- [x] https://github.com/testing-library/eslint-plugin-testing-library/pull/468

### ✅ `no-wait-for-multiple-assertions`

Enable for all configs

- [x] https://github.com/testing-library/eslint-plugin-testing-library/pull/483

### ✅ `no-wait-for-side-effects`

Enable for all configs

- [x] https://github.com/testing-library/eslint-plugin-testing-library/pull/484

### ✅ `no-wait-for-snapshot`

Enable for all configs

- [x] https://github.com/testing-library/eslint-plugin-testing-library/pull/485

### ✅ `prefer-presence-queries`

Enable for all configs

- [x] https://github.com/testing-library/eslint-plugin-testing-library/pull/486

### ✅ `prefer-query-by-disappearance`

Enable for all configs

- [x] https://github.com/testing-library/eslint-plugin-testing-library/pull/487

## ✅ Make `isStrict` option `true` by default for `no-unnecessary-act`

We have enabled this rule with `isStrict` to true in the shared configs, this option is still false by default. We should change it so it's true by default.

- [x] https://github.com/testing-library/eslint-plugin-testing-library/pull/479

## 🕐 Rules rename

We have some inconsistencies in naming some of our rules regarding using singular/plural.

### ✅ `no-debug` -> `no-debugging-utils`

- [x] https://github.com/testing-library/eslint-plugin-testing-library/pull/469

**Comment by MichaelDeBoey** [comment]
> ### Enable more rules in the shared configs
>
> I think we should enable these rules too:
> - testing-library/no-render-in-setup
> - testing-library/no-unnecessary-act (✅ done already)
> - testing-library/no-wait-for-multiple-assertions
> - testing-library/no-wait-for-side-effects
> - testing-library/no-wait-for-snapshot
> - testing-library/prefer-presence-queries
> - testing-library/prefer-query-by-disappearance

Do we enable them in all configs or only in specific framework configs?

> ### [no-unnecessary-act] Set `isStrict` to true by default
>
> We have enabled this rule with `isStrict` to true in the shared configs, this option is still false by default. We should change it so it's true by default.

This means we can just make `no-unnecessary-act` an `error` in the React config

> ### Rules renaming for consistency
>
> We have some inconsistencies in naming some of our rules regarding using singular/plural.
> 
> At the moment we have:
> - await-async-**query**
> - no-await-sync-**query**
> - prefer-presence-**queries**
> - prefer-**query**-by-disappearance
> - prefer-screen-**queries**
> 
> So query could have two meanings: the verb (to query) and the noun (a query). I think we should use the singular for the verb and the plural for the noun. All our usages are nouns, so all of them should be plural perhaps?
> 
> - await-async-**queries**
> - no-await-sync-**queries**
> - prefer-presence-**queries**
> - prefer-**queries**-by-disappearance
> - prefer-screen-**queries**

I think we should keep `prefer-query-by-disappearance` as this is about the specific `queryBy*` queries.  
All others are more generic, so those are better to be made consistent indeed.

**Comment by Belco90** [comment]
> Do we enable them in all configs or only in specific framework configs?

I'd say in all applicable ones:

- testing-library/no-render-in-setup: angular, react and vue (dom doesn't have a `render` method)
- testing-library/no-wait-for-multiple-assertions: all
- testing-library/no-wait-for-side-effects: all
- testing-library/no-wait-for-snapshot: all
- testing-library/prefer-presence-queries: all
- testing-library/prefer-query-by-disappearance: all


> This means we can just make `no-unnecessary-act` an `error` in the React config

Indeed!


> I think we should keep `prefer-query-by-disappearance` as this is about the specific `queryBy*` queries.
> All others are more generic, so those are better to be made consistent indeed.

As you mentioned, _this is about the specific `queryBy*` queries_ so that's why I suggested renaming to "queries" in that one too.
