### ISSUE TITLE
strange error for changing the name of screen object

### ISSUE THREAD

**Issue by sinafath** [testing-library/eslint-plugin-testing-library#493]
### Plugin version

^4.12.4

### ESLint version

7.32.0

### Node.js version

v14.17.6

### npm/yarn version

6.14.15

### Operating system

linux

### Bug description

i see an error because I changed the name of  `screen` object to `rtlScreen`
```
import { render, screen as rtlScreen } from "@testing-library/react";
import Login from "../pages/login";

function setUpLogin() {
  render(<Login />);
  let phoneNumber = rtlScreen.getByLabelText(/phone number/i);
  let password = rtlScreen.getByLabelText(/password/i);
  let submit = rtlScreen.getByRole("button", { name: /submit/i });
  return { phoneNumber, password, submit };
}

test("renders form", () => {
  const screen = setUpLogin();
  expect(screen.phoneNumber).toBeInTheDocument();
  expect(screen.password).toBeInTheDocument();
  expect(screen.submit).toBeInTheDocument();
});

```

### Steps to reproduce

change the name of `screen` to `screenrtl` and use `screenrtl` like `screenrtl.getByLabelText`

### Error output/screenshots

![Screenshot_20211002_215719](https://user-images.githubusercontent.com/83284138/135727925-099710ae-75e2-498c-ac93-e531a0ed12e0.png)

### ESLint configuration

{
  "plugins": ["testing-library"],
  "extends": ["next/core-web-vitals","plugin:testing-library/react"],
  "rules": {
    "testing-library/await-async-query": "error",
    "testing-library/no-await-sync-query": "error",
    "testing-library/no-debug": "warn",
    "testing-library/no-dom-import": "off",
    "testing-library/prefer-find-by": "warn"
  }
}

### Rule(s) affected

Avoid destructuring queries from `render` result, use `screen.getByLabelText` instead

### Do you want to submit a pull request to fix this bug?

No

**Comment by Belco90** [comment]
Hi @sinafath!

If I understood correctly, the plugin is reporting an error when renaming `screen` import right?

```js
import { render, screen as rtlScreen } from "@testing-library/react";
//                          ^^^^ this screen is reported
```

**Comment by sinafath** [comment]
@Belco90
yes

**Comment by Belco90** [comment]
Any reason for closing the issue? 🤔
