### ISSUE TITLE
Show eslint warnings/errors in vscode?

### ISSUE THREAD

**Issue by kelly-tock** [testing-library/eslint-plugin-testing-library#555]
### Plugin version

5.0.3

### ESLint version

8.6.0

### Node.js version

16.13.2

### npm/yarn version

yarn 1.22.17

### Operating system

macOS Monterey 12.2.1

### Bug description

I have this plugin installed and configured. I would expect to see warnings in my test files in vscode, but don't. I do see them when I run them on the command line. 

### Steps to reproduce

install 
https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint
into vscode. 

set up a basic eslint config, and write a test. I am able to see the errors when run in the command line, but not in vscode. 

### ESLint configuration
```js
const fs = require('fs');
const path = require('path');

const schemaString = fs.readFileSync(
  path.resolve(__dirname, '../server/dist/schema.graphqls'),
  'utf8'
);

module.exports = {
  extends: ['@tock'],
  root: true,
  plugins: ['testing-library', 'jest-dom'],
  rules: {
    'graphql/template-strings': ['error', { env: 'apollo', schemaString }],
    'jsx-a11y/no-static-element-interactions': 'off',
    'jsx-a11y/tabindex-no-positive': 'off',
    'jsx-a11y/no-autofocus': 'off',
    'jsx-a11y/label-has-associated-control': 'off',
    'jsx-a11y/anchor-is-valid': 'off',
    'no-restricted-imports': [
      'warn',
      {
        paths: [
          {
            name: '@material-ui/core',
            importNames: [
              'Button',
              'Dialog',
              'DialogActions',
              'DialogContent',
              'DialogTitle',
              'Divider',
              'Drawer',
              'Grid',
              'Tooltip',
              'Typography',
              'makeStyles',
              'Theme',
              'createStyles',
              'WithStyles',
              'withStyles',
            ],
            message:
              "Please import from from 'ui' instead. For styles and theme related imports, import from from '@material-ui/core/styles' instead.",
          },
          {
            // These are fine to import in a local branch, but not meant to be merged into master.
            name: 'shared/utils/devUtils',
          },
        ],
      },
    ],
  },
  overrides: [
    {
      files: ['**/__tests__/**/*.[jt]s?(x)', '**/?(*.)+(spec|test).[jt]s?(x)'],
      extends: ['plugin:testing-library/react', 'plugin:jest-dom/recommended'],
      rules: {
        'testing-library/no-node-access': 'off',
      },
    },
  ],
};
```
### Rule(s) affected

all are affected in vscode but not in command line. 

### Anything else?

here's the command that will show errors/warnings for tests:

```
npx eslint --cache --cache-location ./.eslint-cache -c .eslintrc.js --no-eslintrc --max-warnings 0 'src/*/js/**/*.{ts,tsx}' '../shared/src/js/**/*.{ts,tsx}' 'test/client/js/**/*.{ts,tsx}'
```

### Do you want to submit a pull request to fix this bug?

No

**Comment by kelly-tock** [comment]
should I log it in that plugin's repo then?  I wasn't quite sure. I see other eslint related things in test files, all except ones that are related to this plugin, so I wondered if there is something different in the way it reports issues maybe?  but i'm not familiar with how plugins do that so wasn't sure. happy to cross post?

**Comment by Belco90** [comment]
Can you try to extend from `plugin:testing-library/react` in the root of the `.eslintrc` file rather than within `overrides` property to see if that makes a difference? If not, I'd create an issue in the vscode plugin indeed. Happy to cross post!

**Comment by kelly-tock** [comment]
ok, so some progress. If I extend from the root, I do get those showing, but that negates what I need to do in terms of the config. as mentioned in this read me, the overrides is the best way to say do this for only these file patterns. I did find I had an eslint config in the directory for tests, and when I put the rules only in there at the root, it shows up in vscode. maybe sharing my config that's in the test directory would illustrate, maybe i'm not seeing something:

```
//inside test directory that is a sibling to project root eslintrc.js

module.exports = {
  root: true,
  extends: ['@tock'],
  globals: {
    DISABLE_CLIENT_SIDE_TIMEOUT: 'readonly',
    __ENV__: 'readonly',
  },
  plugins: ['xss'],
  rules: {
    '@typescript-eslint/no-var-requires': 'off',
    'xss/no-location-href-assign': [
      2,
      {
        escapeFunc: 'dontDoIt_JustUseAnchor',
      },
    ],
  },
};
```

**Comment by Belco90** [comment]
Yeah, I understand your use case. Just wanted to see if we could spot something else by extending the plugin outside the `overrides` section.

Oh, I see. If you have another ESLint config file that can take more priority than the `overrides` property from the main config file (I don't remember the exact order for this right now). You need to stick to just one of those 2 ways then: or enabling `eslint-plugin-testing-library` in the overrides of the main one and removing the test config one, or remove `eslint-plugin-testing-library` from the main config file and enable it in the test config file.

Is it 100% solved then?

**Comment by kelly-tock** [comment]
yeah, I have what I consider a workaround. my guess is the plugin is taking only the one in that directory that it finds.
