### ISSUE TITLE
Allow exceptions for "no-node-access"

### ISSUE THREAD

**Issue by alexey-kozlenkov** [testing-library/eslint-plugin-testing-library#593]
### What rule do you want to change?

no-node-access

### Does this change cause the rule to produce more or fewer warnings?

Fewer warnings

### How will the change be implemented?

`render` method returns container which has content rendered inside it (`div` element by default - [docs](https://testing-library.com/docs/react-testing-library/api#:~:text=Tip%3A%20To%20get%20the%20root%20element%20of%20your%20rendered%20element%2C%20use%20container.firstChild.) )

The easiest way to access content itself is by using `firstChild` property
This is hardly avoidable in some cases, such as:
* snapshot testing
* testing if rendering simply has/has not happened
* counting child elements

The rule could ignore `firstChild`(only?) in some cases.

### Example code

```
const MyComponent = () => <div>Any kind of stuff</div>
```

```
describe('some test', () => {
  it('test case', () => {
    const { container } = render(<MyComponent />)

    expect(container.firstChild).toMatchSnapshot()
  })
})
```

### How does the current rule affect the code?

Currently rule highlights `container.firstChild` part as a mistaken direct Node access

### How will the new rule affect the code?

Won't highlight it

### Do you want to submit a pull request to change the rule?

No

**Comment by Belco90** [comment]
Thanks for reporting @alexey-kozlenkov!

I was tempted to suggest an option like `allowedProperties` where you could specify all the properties needed, but that could be use as an escape hatch. So my proposal is to add a new `allowContainerFirstChild` option, which would be a boolean to which prevents reporting `container.firstChild`. What do you think?

What about `no-container`? Does that rule complain about `container.firstChild`?
