### ISSUE TITLE
Replace `prefer-expect-query-by` by better rule

### ISSUE THREAD

**Issue by Belco90** [testing-library/eslint-plugin-testing-library#61]
Motivated by #59 it looks like we need to replace `prefer-expect-query-by`* by better implementation to only force users to replace `getBy` queries by `queryBy` when:

- [asserting elements are not present](https://testing-library.com/docs/guide-disappearance#asserting-elements-are-not-present)
- [waiting for disappearance](https://testing-library.com/docs/guide-disappearance#waiting-for-disappearance)

This should be checked in several cases. A few I can think of at the moment:

- asserting with `.not.toBeInTheDocument()`
- asserting with `.toBeNull()`
- asserting with `.toBe(null)` _this is actually an equivalent for the previous one, probably more variations to cover as `.toBeFalsy()` but I think just this one is enough for now?_
- waiting for disappearance with `waitForElementToBeRemoved`

I can't think better name for this rule than `no-get-by-for-element-absence`, any suggestions?

*_We could maintain `prefer-expect-query-by` when the new rule is implemented, but I think it wouldn't be that useful anymore and could even lead to confusion_

**Comment by thomlom** [comment]
This rule makes more sense to me. I'll write it next week. 
I think the name is fine, I don't have a better idea right now!

About maintaining `prefer-expect-query-by`, I'm in favour of just replacing it with this rule.
