### ISSUE TITLE
Transform `await-fire-event` into `await-async-events`

### ISSUE THREAD

**Issue by Belco90** [testing-library/eslint-plugin-testing-library#626]
Transform `await-fire-event` into `await-async-events`.

Since user-events v14 is async, we should transform this rule to consider both fire and user events.

It needs a new option to decide which modules are enabled or disabled:
- fire-event: disabled by default since it's only used in Vue (enabled in Vue shareable config tho)
- user-event: enabled by default since user-event 14 is async

Explain in the rule's doc that the user-event option must be disabled when working with user-event prior to v14

**Comment by skovy** [comment]
@Belco90 @MichaelDeBoey assuming this was supposed to be plural? I can open a PR to fix it since it's currently `await-async-event`

**Comment by Belco90** [comment]
> @Belco90 @MichaelDeBoey assuming this was supposed to be plural? I can open a PR to fix it since it's currently `await-async-event`

I didn't realize it wasn't plural! Please, open a small PR to rename it 🙏
