### ISSUE TITLE
New rule: Disallow manual cleanups

### ISSUE THREAD

**Issue by Belco90** [testing-library/eslint-plugin-testing-library#63]
The `cleanup` util to unmount React trees mounted with `render` will be call automatically if:

- [testing framework you are using supports global `afterEach`](https://testing-library.com/docs/react-testing-library/api#cleanup)
- [you don't skip the auto cleanup with RTL_SKIP_AUTO_CLEANUP](https://testing-library.com/docs/react-testing-library/setup#skipping-auto-cleanup)

So in order to avoid adding manual cleanups when is automatically setup, we can add a rule to prevent this. It looks like an easy rule to implement that could be named `no-manual-cleanups` that should not be enabled in any shareable config by default.

**Comment by thomlom** [comment]
I think this rule is "easy" to implement to a certain extent. For example, I don't see how you could detect if the user has set `RTL_SKIP_AUTO_CLEANUP` or his testing framework. We could add these settings in the config options of an ESLint rule but it looks unintuitive to me.

If you mean that the rule only detects the `cleanup` keyword and reports it systematically, then yes, it should be pretty straightforward.

**Comment by Belco90** [comment]
No sorry, I didn't mean to detect that at all. I was just elaborating the different scenarios to justify why this rule can't be enabled automatically due to auto cleanup could not be set up.

**Comment by thomlom** [comment]
I'll take care of this rule. By playing with the different cases where the rule should fire, I noticed something.

`cleanup` has to be imported from a `@testing-library` to be used right? So instead of reporting the use of `cleanup` somewhere in the code, why not reporting it immediately as soon as the user imports it? It makes more sense to me that way. What do you think @Belco90 ?

**Comment by Belco90** [comment]
Oh wow, that would be amazing! It would need more stuff to test of course but it makes sense to me.
