### ISSUE TITLE
[Relevant for contributors, not users] Fix linter errors in some files

### ISSUE THREAD

**Issue by sjarva** [testing-library/eslint-plugin-testing-library#642]
### Plugin version

5.6.2

### What problem do you want to solve?

For some reason, there are several files in `main` branch that have linter errors (to mention a few: `lib/rules/await-async-query.ts`, `lib/rules/await-fire-events.ts` and `lib/node-utils/index.ts`).

It would be great to have this solved, so that when a contributor will submit a PR that has bug or new rule related changes to these files, the linter error fixes are not there to complicate the PR review. Also, as a contributor, it has been slightly annoying to work on PRs, when I open these files to check how a function or rule works, and then see my editor highlight the file for a linter error.

### Your take on the correct solution?

Make a PR that fixes linter errors in these files.

### Anything else?

It would be great if a maintainer could look at the linter, lint-staged and husky setups to make sure this doesn't happen again.

### Do you want to submit a pull request to implement this change?

Yes

**Comment by Belco90** [comment]
Thanks for reporting! Let me check this. Our CI should prevent running into issues like this one.

**Comment by Belco90** [comment]
Hi again! Sorry, but I don't see any linter error on `main` branch.

<img width="723" alt="CleanShot 2022-09-08 at 18 32 34@2x" src="https://user-images.githubusercontent.com/2677072/189176711-87164d2d-03b4-43d4-bc76-52b734c41441.png">

Could you double-check? If this keeps happening, could you add some steps to reproduce?

**Comment by sjarva** [comment]
When digging deeper, I realised that this is due to some config of mine (although what, I don't know). Clearing `eslint`'s cache helped.

For some reason my `eslint` thought that [`@typescript-eslint/prefer-optional-chain`](https://typescript-eslint.io/rules/prefer-optional-chain/) is on for this repo. At first I thought that it is part `@typescript-eslint/recommended` ruleset which this repo extends, but nope, that rule is part only of the `strict` ruleset.

Here are some screenshots:

<img width="1230" alt="testing-library npm run lint 5 errors" src="https://user-images.githubusercontent.com/1133238/189191563-60fcf914-7899-40de-be80-08b3e1a17315.png">

<img width="2542" alt="testing-library files open linter errors" src="https://user-images.githubusercontent.com/1133238/189191686-72234564-31a9-4c89-b687-79e0f11b669c.png">

I'm closing this issue, as the cache clearing fixed this.
