### ISSUE TITLE
Add `no-render-in-setup` rationale to docs

### ISSUE THREAD

**Issue by theredspoon** [testing-library/eslint-plugin-testing-library#696]
### Plugin version

5.9.1

### What problem do you want to solve?

The rationale for `no-render-in-setup` is missing from the documentation. 

### Your take on the correct solution?

Let's add the rationale to the documentation. This rationale was referenced in the feature request conversation [here](https://github.com/testing-library/eslint-plugin-testing-library/issues/207#issuecomment-1184596285).

The rationale itself is [here](https://kentcdodds.com/blog/avoid-nesting-when-youre-testing).

### Do you want to submit a pull request to implement this change?

Yes

**Comment by Belco90** [comment]
I assume you meant `no-render-in-setup`?

**Comment by theredspoon** [comment]
Oh gosh, yup. Just saw that mixup.

**Comment by theredspoon** [comment]
Edited the issue and title, thanks for that.
