### ISSUE TITLE
Invalid autofix from `prefer-find-by`

### ISSUE THREAD

**Issue by tylerlaprade** [testing-library/eslint-plugin-testing-library#739]
### Have you read the Troubleshooting section?

Yes

### Plugin version

5.10.2

### ESLint version

8.33.0

### Node.js version

18.14.0

### package manager and version

npm 8.15.0

### Operating system

macOS Ventura 13.0.1

### Bug description

The rule flagged and "fixed" a line containing both `await waitFor` and `getByText`, but there were other functions in between. The autofix removed those other functions, breaking my code.

### Steps to reproduce

1. `await waitFor(() => expect(screen.getByText('foo')).toBeInTheDocument());`
2. ESLint auto-fix
3. `await screen.findByText('foo');`

### ESLint configuration

`"extends": ["plugin:testing-library/react"]`

### Rule(s) affected

`prefer-find-by`

### Do you want to submit a pull request to fix this bug?

No

**Comment by Belco90** [comment]
Duplicated of #579
