### ISSUE TITLE
Contradicting issue reports between `async-await-events` and `no-await-sync-events`

### ISSUE THREAD

**Issue by wadehammes** [testing-library/eslint-plugin-testing-library#801]
### Have you read the Troubleshooting section?

Yes

### Plugin version

latest

### ESLint version

latest

### Node.js version

18.16.1

### package manager and version

pnpm 8.6.12

### Operating system

Macos 13.5

### Bug description

I upgraded to v6 and was first met with this error in my Vercel build:

<img width="1229" alt="image" src="https://github.com/testing-library/eslint-plugin-testing-library/assets/222170/6ff9448e-f6b2-4777-ae75-3edb5e0b89df">

Easy enough. These had no `await` so I added that before each. Thinking I would be in the clear, I wasn't expecting the build to fail. However, I am now getting the opposite error in Vercel:

<img width="1221" alt="image" src="https://github.com/testing-library/eslint-plugin-testing-library/assets/222170/ae6fd8ad-f4f5-424d-b358-3495bdf389d2">

Unsure of what to do here or if this a bug or I need to do some combination of rules config in my eslint. Thanks for the help in advance!

### Steps to reproduce

See above

### ESLint configuration

No rules overridden in ESLint

### Rule(s) affected

`async-await-events` and `no-await-sync-events`

### Do you want to submit a pull request to fix this bug?

No

**Comment by wadehammes** [comment]
I wonder if this relates to https://github.com/testing-library/eslint-plugin-testing-library/issues/669

**Comment by Belco90** [comment]
Hi @wadehammes, thanks for reporting.

Just to confirm, you are extending one of the provided presets without overriding any rule manually, right?

**Comment by wadehammes** [comment]
> Hi @wadehammes, thanks for reporting.
> 
> Just to confirm, you are extending one of the provided presets without overriding any rule manually, right?

Yes - I removed the `extend-expect` library and am importing `@testing-library/jest-dom`. I was getting errors before doing this new import around `toBeInTheDocument` not being a method on `JestMatchers` (if this is what you are talking about), so I think I have it set up properly. No rules are being overridden in eslintrc, correct.

**Comment by wadehammes** [comment]
> Hi @wadehammes, thanks for reporting.
> 
> Just to confirm, you are extending one of the provided presets without overriding any rule manually, right?

yes I am extending `plugin:testing-library/react` in my eslint plugins, no manually overridden rules

Ye

**Comment by Belco90** [comment]
I'll take care of this one next week (hopefully).

**Comment by Belco90** [comment]
@fabb can you create a new issue for it? So you can describe better the problem.

**Comment by tay1orjones** [comment]
v6.0.1 fixed it for us, thanks!
