### ISSUE TITLE
Failure to Detect no-node-access Error Upon Re-Export of '@testing-library/react'

### ISSUE THREAD

**Issue by y-hsgw** [testing-library/eslint-plugin-testing-library#802]
### Have you read the Troubleshooting section?

Yes

### Plugin version

6.0.0

### ESLint version

8.47.0

### Node.js version

18.16.0

### package manager and version

9.7.1

### Operating system

macOS Ventura 13.4.1（22F82）

### Bug description

Following the instructions in the [custom-render ](https://testing-library.com/docs/react-native-testing-library/setup/#custom-render
)section, I have created a test-utils.ts file and re-exported '@testing-library/react' within it to utilize the API of '@testing-library/react'. However, it seems that the ESLint plugin's ability to detect the "no-node-access" error becomes inconsistent when using imports from '@testing-library/react'.

`test-utils.ts`
```typescript
import { ThemeProvider } from '@mui/material';
import { RenderOptions, render } from '@testing-library/react';

const AllTheProviders: React.FC<{ children: React.ReactNode }> = ({ children }) => (
  <ThemeProvider theme={theme}>{children}</ThemeProvider>
);

const customRender = (ui: React.ReactElement, options?: Omit<RenderOptions, 'wrapper'>) =>
  render(ui, { wrapper: AllTheProviders, ...options });

export * from '@testing-library/react';
export { customRender as render };
```

https://github.com/testing-library/eslint-plugin-testing-library/assets/49516827/de0b50f1-db7d-4209-886a-50380c02150c

### Steps to reproduce

1. Create a test-utils.ts file as directed in the custom-render section.
2. Inside the test-utils.ts file, export '@testing-library/react' and utilize its APIs.
3. Observe the ESLint behavior regarding the "no-node-access" error when using imports from '@testing-library/react' within this context.

### ESLint configuration

```javascript
{
  "extends": [
    "next/core-web-vitals",
    "plugin:@typescript-eslint/recommended",
    "prettier"
  ],
  "rules": {
    "prefer-template": "error"
  },
  "overrides": [
    {
      "files": ["*.test.{ts,tsx}"],
      "extends": ["plugin:jest/recommended", "plugin:testing-library/react"]
    }
  ]
}
```

### Rule(s) affected

```javascript
  "overrides": [
    {
      "files": ["*.test.{ts,tsx}"],
      "extends": ["plugin:jest/recommended", "plugin:testing-library/react"]
    }
  ]
```

### Do you want to submit a pull request to fix this bug?

No

**Comment by Belco90** [comment]
Hi @y-hsgw. This behavior is intended, let me elaborate on this.

This rule is pretty aggressive itself, so we got an issue about limiting the errors reported about it #334. In #338 we limited the scope of the rule so errors are reported only if an actual Testing Library module or a explicit custom one are found. You can read more about it in [this comment within the code](https://github.com/testing-library/eslint-plugin-testing-library/blob/8dfe155f5658c14004c80ddef274171e1d2950b1/lib/rules/no-node-access.ts#L47).

You can fix it by declaring `@/test/test-utils` in [the utils-module setting](https://github.com/testing-library/eslint-plugin-testing-library#testing-libraryutils-module). We probably need to explain this in the rule's doc itself, so it's not hidden in the code itself.

**Comment by y-hsgw** [comment]
Hi @Belco90.

Thank you so much for your response. Your provided information helped me resolve the issue. Your detailed explanation was incredibly helpful and I truly appreciate it.

Thank you again for taking the time to reply amidst your busy schedule.
