### ISSUE TITLE
RFC: fixer for `wait` (V7)

### ISSUE THREAD

**Issue by timdeschryver** [testing-library/eslint-plugin-testing-library#86]
Would it be an option to add a fixable rule for the changes made to `wait`?
The implementation could look like [this](https://astexplorer.net/#/gist/52cd2d7008f89a1baa11819d361f3bb5/22406c2aef432778000274ff6178e0b11ba7b543)

```js
export default function(context) {
  return {
    "CallExpression > Identifier[name=wait]"(node) {
      context.report({
        node: node,
        message: "waitForRename",
        fix: fixer => fixer.replaceText(node, "waitFor")
      });
    },
    "CallExpression[callee.name=waitFor][arguments.length=0]"(node) {
      context.report({
        node: node,
        message: "emptyCallBack",
        fix: fixer => fixer.replaceText(node, "waitFor(() => {})")
      });
    }
  };
}
```

input:

```js
async () => {
	await wait(() => {});
  	await wait();
}
```

output:

```js
async () => {
	await waitFor(() => {});
  	await waitFor(() => {});
}
```

**Comment by Belco90** [comment]
This seems really interesting! I guess the rule could be called something like `prefer-wait-for` and we could also check `waitForDomChange` right? The replace would be the same I think.

I'll give it a try tomorrow.

**Comment by timdeschryver** [comment]
@Belco90 yep that should work, see the [updates astexplorer](https://astexplorer.net/#/gist/52cd2d7008f89a1baa11819d361f3bb5/3af4f03d819d38374c8eb1084d5dab70a44588b3) for an implementation of the rule

**Comment by Belco90** [comment]
This will be released on v3
