### ISSUE TITLE
Upgrade `@typescript-eslint/utils` to v7

### ISSUE THREAD

**Issue by Belco90** [testing-library/eslint-plugin-testing-library#897]
- Upgrade `typescript-eslint` packages to v7
- Drop support for ESLint v7 and v8

**Comment by nathanmmiller** [comment]
@Belco90 this is probably a fairly huge undertaking. Is there any appetite for a simple patch release that would at least bump to v6, which seems like it could be a smaller step in the right direction?

**Comment by burtek** [comment]
NB: typescript-eslint v8 is already stable at this point
