### ISSUE TITLE
New rule: no-wait-for-empty-cb

### ISSUE THREAD

**Issue by Belco90** [testing-library/eslint-plugin-testing-library#92]
New `waitFor` method added in [dom-testing-library v7](https://github.com/testing-library/dom-testing-library/releases/tag/v7.0.0) introduces a new restriction on empty async utils: a callback must be passed as param. Empty callbacks are allowed but not recommended. Quoting changelog itself:

> it's recommended to avoid an empty callback and instead insert an assertion in that callback function. This is because otherwise your test is relying on the "next tick of the event loop" before proceeding, and that's not consistent with the philosophy of the library:

Because of that, a new rule called `no-wait-for-empty-cb` could enforce to pass non-empty callbacks to `waitFor`.

What would be considered a non-empty callback tho? I would say any of these:

- empty arrow function (i.e. `() => {}`)
- empty regular function (i.e. `function () {}`)
- a var referencing any of previously mentioned
- a function or var called `noop`?
- falsy values?

**Comment by Belco90** [comment]
@thomlom @emmenko thoughts?

**Comment by timdeschryver** [comment]
I'll try to implement this one !

**Comment by timdeschryver** [comment]
Could we reuse this one? https://github.com/eslint/eslint/blob/master/lib/rules/no-empty-function.js
And just do the check for the wait functions?

**Comment by Belco90** [comment]
Of course! Didn't realize ESLint already has a rule for empty functions! How are you planning to reuse it tho? I don't know if there is a way to _extend_ rules but that would be ideal.

**Comment by timdeschryver** [comment]
I was just about to copy paste it 😅
Just fyi, I think you should be able to extend it (like I did but for tslint at [ngrx-tslint-rules](https://github.com/timdeschryver/ngrx-tslint-rules/blob/master/src/recommended.ts#L2)) but then it will warn on every empty callback, not only for the wait functions

**Comment by Belco90** [comment]
I see. I thought ESLint had a more fancy way of doing that, but that's probably too much magic haha.

**Comment by Belco90** [comment]
This will be released on v3
