### ISSUE TITLE
ESLint v9 still not supported?

### ISSUE THREAD

**Issue by obrejla** [testing-library/eslint-plugin-testing-library#936]
### Have you read the Troubleshooting section?

Yes

### Plugin version

v6.3.0

### ESLint version

v9.12.0

### Node.js version

20.11.1

### package manager and version

yarn 1.22.18

### Operating system

macOS

### Bug description

ESLint v8.x is already deprecated - at its [end of life](https://eslint.org/blog/2024/09/eslint-v8-eol-version-support/#eslint-v8.x-end-of-life-is-october-5%2C-2024), and we can't upgrade to v9.x because testing-library plugin does not support eslint v9.x.

### Steps to reproduce

Just try to use eslint-plugin-testing-library with eslint v9.x, not possible.

### Error output/screenshots

`TypeError: context.getScope is not a function` error.

### ESLint configuration

Common configuration.

### Rule(s) affected

e.g. `Rule: "testing-library/no-container"`

### Do you want to submit a pull request to fix this bug?

No

**Comment by Belco90** [comment]
Will be fixed by #925
